palabra=input("Escribe una palabra: ")
num_int=int(input("Escribe un número entero: "))
num_float=float(input("Escribe un número decimal: "))
num_complex=complex(input("Escribe un número imaginario: "))
print("")
print("String: ", palabra)
print("Número entero: ", num_int)
print("Número decimal: ", num_float)
print("Número imaginario: ", num_complex)
